# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build Application

on:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
  workflow_dispatch:
  schedule:
    - cron:  '30 17 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # external action which clones the current directory in the 
    # virtual machine
    - uses: actions/checkout@v2 
    
    # external action to install Flutter stable on the virtual machine
    - uses: subosito/flutter-action@v2 
      with:
        channel: stable

    # is always useful to know the Flutter version
    - run: flutter --version

    # dependencies installation
    - run: flutter pub get

    # static analysis check
    - run: flutter analyze

    # tests check
    - run: flutter test
